[package]
name = "manta-cli"
version = "0.1.0"
edition = "2021"
authors = ["Manta Network <contact@manta.network>"]
readme = "README.md"
license-file = "LICENSE"
repository = "https://github.com/Manta-Network/cli"
homepage = "https://github.com/Manta-Network"
documentation = "https://github.com/Manta-Network/cli"
categories = [""]
keywords = [""]
description = "Command Line Tools for Interacting with Manta Protocols"
publish = false

[package.metadata.docs.rs]
# To build locally:
# RUSTDOCFLAGS="--cfg doc_cfg" cargo +nightly doc --all-features --open
all-features = true
rustdoc-args = ["--cfg", "doc_cfg"]

[badges]
is-it-maintained-issue-resolution = { repository = "Manta-Network/cli" }
is-it-maintained-open-issues = { repository = "Manta-Network/cli" }
maintenance = { status = "actively-developed" }

[dependencies]
clap = { version = "3.1.12", default-features = false, features = ["color", "derive", "std", "suggestions", "unicode", "wrap_help"] }
clap-verbosity-flag = { version = "1.0.0", default-features = false }
derivative = { version = "2.2.0", default-features = false, features = ["use_core"] }
derive_more = { version = "0.99.17", default-features = false, features = ["display", "error", "from_str"] }
manta = { git = "https://github.com/manta-network/Manta", default-features = false }
manta-signer = { git = "https://github.com/manta-network/manta-signer", branch = "manta-rs-integration", default-features = false }
manta-util = { git = "https://github.com/manta-network/manta-rs", default-features = false }
wild = { version = "2.0.4", default-features = false }

[build-dependencies]
clap_mangen = { version = "0.1.6", default-features = false }
clap_complete = { version = "3.1.2", default-features = false }

